### ISSUE TITLE
Release notes and tag for v1.21.0 missing

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/cflinuxfs2-rootfs-release#2]
Hi, Buildpacks team,

When I was filling out the CF v240 release notes, which include links to release notes for related releases such as this one, I noticed that the release notes and tag for v1.21.0 were missing (see screenshots). The BOSH release does exist, though: it's [listed on bosh.io](https://bosh.io/releases/github.com/cloudfoundry/cflinuxfs2-rootfs-release?version=1.21.0), and [ran through the Runtime pipeline for the CF v240 release candidate](https://github.com/cloudfoundry/diego-cf-compatibility/blob/master/compatibility-v4.csv#L90). Could we please ensure that those are published? Thanks!
<img width="377" alt="screen shot 2016-08-09 at 2 34 20 pm" src="https://cloud.githubusercontent.com/assets/5836757/17534560/9a5abfe4-5e3e-11e6-8817-b95e87a982cc.png">
<img width="1032" alt="screen shot 2016-08-09 at 2 34 38 pm" src="https://cloud.githubusercontent.com/assets/5836757/17534559/9a5888b4-5e3e-11e6-8649-cfb095e354c4.png">

Best,
Eric, CF Runtime Diego PM

**Comment by sclevine** [comment]
Seems like the [corresponding 1.72.0 stacks release](https://github.com/cloudfoundry/stacks/releases/tag/1.72.0) for v1.21.0 had no changes and was cut accidentally. I assume this means v1.20.0 is the same as v1.21.0. I'll review this with Danny / the team.

**Comment by emalm** [comment]
Thanks, @sclevine!

**Comment by sclevine** [comment]
Release notes published.
