### ISSUE TITLE
Updating with a new stack not supported? 

### ISSUE THREAD

**Issue by tomoe** [cloudfoundry/cflinuxfs2-rootfs-release#3]
Looking at [pre-start](https://github.com/cloudfoundry/cflinuxfs2-rootfs-release/blob/master/jobs/cflinuxfs2-rootfs-setup/templates/pre-start), it's just un-taring when `[ ! -d $ROOTFS_DIR ]`. 
Does that mean, stack deployment always assumes a fresh environment? i.e. updating not supported? maybe stack update implies stemcell update, which would always cause a deployment on a new VM?

**Comment by emalm** [comment]
Hi, @tomoe,

The full rootfs directory is `/var/vcap/packages/cflinuxfs2/rootfs`, but `/var/vcap/packages/cflinuxfs2` is a symlink to a specific version of the `cflinuxfs2` package (for example, `/var/vcap/data/packages/cflinuxfs2/a48cedf96fa738616b8f3a36980a5cac60a7e909.1-aa783c48dc40730ce51e3ae119ec18b8903b0c74`). So if the rootfs contents are updated, the package version will be different, and `/var/vcap/packages/cflinuxfs2` will not have a rootfs subdirectory after BOSH updates the VM with the new package.

Best,
Eric, CF Runtime Diego PM

**Comment by tomoe** [comment]
Thanks for the thorough explanation, @ematpl !
Closing as it's my misunderstanding.

**Comment by emalm** [comment]
To be fair, that's a subtle enough BOSH-ism that it may be worthy of a succinct comment. :)

**Comment by tomoe** [comment]
:-) I need to be more brainwashed by BOSH-ism
